[package]
name = "rust_ping"
version = "0.1.0"
authors = ["shyamp99 <shyamp99@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.25.0"
dns-lookup = "1.0.1"
rand = "0.7.3"
ctrlc = "3.1.4"
